[package]
name = "solana-enrollment-app"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.17"
solana-client = "1.17"
solana-program = "1.17"
borsh = "0.10.3"
bs58 = "0.5.0"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }